" vimrc file {{{
function Vimrc()
   find $VIMRUNTIME\..\_vimrc
endfunction
" }}}

" source $VIMRUNTIME/vimrc_example.vim
" source $VIMRUNTIME/mswin.vim
" behave mswin

set nocompatible

" Plugins {{{
filetype off
command! PU PlugUpdate | PlugUpgrade
call plug#begin('C:\Program Files (x86)\Vim\vim81\plugged')

Plug 'junegunn/vim-plug'

" UltiSnips {{{

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltisnipsJumpBackwardTrigger="<c-z>"
let g:UltisnipsEditSplit="vertical"
let g:UltisnipsSnippetDir= "C:/Users/aaron/Ultisnips"
" let g:UltisnipsSnippetDirectories=["C:/Users/aaron/Ultisnips"]
" }}}

"  NerdTree {{{
Plug 'scrooloose/nerdtree'

let NERDTreeIgnore = ['__pycache__', '\.pyc$', '\.o$', '\.so$', '\.a$', '\.swp', '*\.swp', '\.swo', '\.swn', '\.swh', '\.swm', '\.swl', '\.swk', '\.sw*$', '[a-zA-Z]*egg[a-zA-Z]*', '.DS_Store', '\.DAT*', '.gitconfig', '\.exe', '_viminfo', 'ntuser.ini']

let NERDTreeShowHidden=1
let g:NERDTreeWinPos="left"
let g:NERDTreeDirArrows=0
map <C-T> :NERDTreeToggle<CR>
" }}}

" tpope {{{
Plug 'tpope/vim-surround'

Plug 'tpope/vim-commentary'

Plug 'tpope/vim-repeat'

Plug 'tpope/vim-vividchalk'
" }}}

" vim-sort-motion {{{
Plug 'christoomey/vim-sort-motion'

let g:sort_motion_flags="ui"
" }}}

call plug#end()

filetype plugin indent on

" }}}

" Basic settings {{{
set encoding=utf-8

set path+=**
set wildmenu
set wildignore+=*/AppData/*,*/.ipython/*,*/3D\ Objects/*,*/Backup/*,*/Contacts/*,*/Cookies/*,*/Druckumgebung/*,*/Favorites/*,*/IntelGraphicsProfiles/*
set wildignore+=*/Links/*,*/Lokale\ Einstellungen/*,*/MicrosoftEdgeBackups/*,*/Music/*,*/Netzwerkumgebung/*,*/OneDrive/*,*/Pictures/*
set wildignore+=*/Recent/*,*/Saved\ Games/*,*/Searches/*,/*SendTo/*,*/Startmenü/*,*/Videos/*,*/Vorlagen/*

set guifont=Consolas:h11:b:cANSI:qDRAFT
set fillchars+=vert:\$
colorscheme vividchalk
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set lines=999 columns=999

set ruler laststatus=2
set hidden
set foldmethod=marker

set splitbelow
set splitright

set number
set relativenumber

set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

set backspace=indent,eol,start whichwrap+=<,>,[,]
" }}}

" Syntax {{{
syntax enable
" set spelllang=en,de
"}}}

" Backup and swap {{{
set noswapfile
set undofile
set undodir=$HOME/vim/undo
set backupdir=$HOME/vim/backup
" }}}

" Autocommands {{{
set updatetime=500
autocmd CursorHold * if @% != "" | update | endif
autocmd BufLeave * if &modifiable | %s/\s\+$//e | endif
" }}}

" mappings {{{
let mapleader=","

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

nnoremap <Space><Space> /<++><CR>"_c4l
nnoremap <C-Space><C-Space> ?<++><CR>"_c4l

" backspace in visual mode
vnoremap <BS> d

" CTRL-backspace in insert
inoremap <C-BS> <Space><C-O>db<BS>

" CTRL-X in visual
vnoremap <C-X> "+x

" CTRL-C in visual
vnoremap <C-C> "+y

" CTRL-V for pasting
vnoremap <C-V> "+gP
" inoremap <C-V> <Space><ESC>"+gPa<BS>
inoremap <C-V> <Space><C-o>"+gP<BS>
cmap <C-V> <C-R>+

" CTRL-Q for visual block mode
noremap <C-Q> <C-V>

" CTRL-U for character codes
inoremap <C-U> <C-V>

" CTRL-S for saving
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

" S-Arrows for selection
nmap <S-K> gh<Up>
nmap <S-J> gh<Down>
smap <S-K> <Up>
smap <S-J> <Down>

" ~ for help like <S-T> did
nnoremap ~ <S-K>

" CTRL-Tab is Next window
nnoremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
cnoremap <C-Tab> <C-C><C-W>w
onoremap <C-Tab> <C-C><C-W>w

" CSS
autocmd FileType css inoremap { {<CR><CR><BS>}<ESC>ki<TAB>

" Python
autocmd Filetype python map <Leader>p <ESC>Iprint(<ESC>A)<ESC>

" Java
autocmd Filetype java nmap <Leader>c :1read $VIMRUNTIME\snippets\java_class<CR>ggdd
autocmd Filetype java nmap <Leader>p ASystem.out.println();<ESC>hci)
autocmd Filetype java nmap <F5> :!javac %<CR>
autocmd Filetype java nmap <F6> :!java %:r<CR>
autocmd Filetype java nmap <F11> :!javac % & java %:r<CR><CR>

" LaTex
let g:tex_flavor='latex'
autocmd FileType tex nmap <F5> :!start cmd /c "pdflatex %"<CR>
autocmd FileType tex nmap <F6> :!start cmd /c "pdflatex ../Zusammenfassung"<CR>
autocmd FileType tex nmap <F7> :!start cmd /c "pdflatex ../%:p:h:t"<CR>
"10@a@s
" }}}
